# Generated by Django 2.1 on 2018-08-12 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='attendee',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='course_id',
            new_name='course',
        ),
    ]
