# Generated by Django 2.1 on 2018-09-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainerapp', '0002_auto_20180812_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('last_name', 'first_name')},
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(default='2018-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default='2018-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
