# Generated by Django 2.1 on 2018-09-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainerapp', '0003_auto_20180929_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_datetime',
        ),
    ]
